sudo: required

language: scala

jdk:
- oraclejdk8

services:
- docker

before_install:
- docker pull quay.io/coreos/etcd:v2.2.5
- docker run -d -p 2379:2379 quay.io/coreos/etcd:v2.2.5 -advertise-client-urls http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379
- docker pull progrium/consul
- docker run -d -p 8500:8500 progrium/consul -server -bootstrap

script: sbt test
